### ISSUE TITLE
Hardware + training time?

### ISSUE THREAD

**Issue by bkj** [wgcban/ddpm-cd#10]
Hello --

Are you able to share what hardware you used to train the model described in your paper, and what the wall-clock training time was?

Thanks!

**Comment by wgcban** [comment]
@bkj 

All experiments used one NVIDIA RTX 8000 (48GB memory) GPU. 

I remember that training the diffusion model took at least 3-4 days, but if you can train it longer, you will get better results. 

Training the change detection classifier is relatively fast, and it depends on the dataset size.

**Comment by Cassiatora** [comment]
@wgcban hi，I want to know the data batchsize during training the diffusion model. And the batchsize of the code is 8?

**Comment by wgcban** [comment]
@yes, we used the same batchsize during the experiments.

**Comment by Cassiatora** [comment]
@wgcban This batchsize is 8, but there are millions of pictures in Google Earth, is it iterated to 1,000,000 steps before passing an epoch. How many epochs are there at the end of training?

**Comment by wgcban** [comment]
@Cassiatora As I remember, I trained it for very long time, perhaps one-two weeks.

**Comment by wgcban** [comment]
@Cassiatora I will confirm the exact batch size I used during the training soon. But I increased the batch size such that it fits to 48 GB GPU.
