### ISSUE TITLE
ddpm_cd

### ISSUE THREAD

**Issue by redwangwangwang** [wgcban/ddpm-cd#13]
Thank you for your great work! What part of the code did you add noise to the image when you were training the CD？

**Comment by wgcban** [comment]
Hi @redwangwangwang 

The main function the we used to obtain the features of noisy pre-change and post-change images here:

https://github.com/wgcban/ddpm-cd/blob/b0213c0049bab215e470326d97499ae69416a843/model/model.py#L80-L92

As you can see, we pass the time-step `t` as an argument that essentially defines the amount of noise variance. This function calls `self.netG.feats`, which returns the features of noisy pre-change and post-change images. The `self.netG.feats` function is written here:

https://github.com/wgcban/ddpm-cd/blob/b0213c0049bab215e470326d97499ae69416a843/model/sr3_modules/diffusion.py#L243-L271

The noise is added to the pre-change and post-change image according to the specified noise variance here:
https://github.com/wgcban/ddpm-cd/blob/b0213c0049bab215e470326d97499ae69416a843/model/sr3_modules/diffusion.py#L266-L267
