### ISSUE TITLE
Freeze module

### ISSUE THREAD

**Issue by wenyihan4396** [wgcban/ddpm-cd#15]
Thank you for your great job!
Could you please tell me where the code which freezes the DDPM's weights?
I want to train the DDPM and CD at the same times.
Best regards

**Comment by wgcban** [comment]
@wenyihan4396 
We get features from the DDPM model here: https://github.com/wgcban/ddpm-cd/blob/b0213c0049bab215e470326d97499ae69416a843/ddpm_cd.py#L123

Above calls ``get_feats()`` https://github.com/wgcban/ddpm-cd/blob/b0213c0049bab215e470326d97499ae69416a843/model/model.py#L80:  inside this you can see the ``torch.no_grad()``.

**Comment by wenyihan4396** [comment]
thank you for your reply!!😄
