### ISSUE TITLE
A question about multi-scale feature representations

### ISSUE THREAD

**Issue by yanzhiHu996** [wgcban/ddpm-cd#16]
Thank you for your great work! What part of the code did you get Multi-scale feature representations from the diffusion decoder?

**Comment by wgcban** [comment]
Hi @yanzhiHu996 Thank you for your interest in our work. We obtain the multi-scale feature representations from the diffusion model here: https://github.com/wgcban/ddpm-cd/blob/b0213c0049bab215e470326d97499ae69416a843/ddpm_cd.py#L123

which uses following function:
https://github.com/wgcban/ddpm-cd/blob/b0213c0049bab215e470326d97499ae69416a843/model/model.py#L80-L92

where we save features during the forward pass here: 
https://github.com/wgcban/ddpm-cd/blob/b0213c0049bab215e470326d97499ae69416a843/model/ddpm_modules/unet.py#L220-L243
