### ISSUE TITLE
about Creating train dataloader.

### ISSUE THREAD

**Issue by Cassiatora** [wgcban/ddpm-cd#17]
![image](https://user-images.githubusercontent.com/58909848/223936554-d378646d-7df1-4b61-bfd7-2725e9f10ea5.png)
The creating train dataloader lasted a long time. I am not sure that is correct.

**Comment by wgcban** [comment]
@Cassiatora This is not normal. Which means maybe the dataloader might be stuck in a loop.  Maybe something wrong with your environment.
