### ISSUE TITLE
about fe_A_t, fd_A_t

### ISSUE THREAD

**Issue by Cassiatora** [wgcban/ddpm-cd#18]
Hi,
Thank you for your great work. I want to konw the meaning of fe_A_t, fd_A_t, and opt['model_cd']['feat_type'].

**Comment by wgcban** [comment]
Hi @Cassiatora 

fe_A_t and fd_A_t denote the encoder and decoder feature representations of pre-change image (A) for timestep t. Similarly, fe_B_t, and fe_B_t denote the encoder and decoder feature representations of post-change image (B) for timestep t.

defined as in here:
https://github.com/wgcban/ddpm-cd/blob/b0213c0049bab215e470326d97499ae69416a843/model/model.py#L84-L92

**Comment by wgcban** [comment]
The opt['model_cd']['feat_type'] specifies whether you want encoder (enc) or decoder (dec) features to consider for the change detection. 
We observed better performance with decoder features. So, default configuration is dec as defined here: https://github.com/wgcban/ddpm-cd/blob/b0213c0049bab215e470326d97499ae69416a843/config/dsifn.json#L62

**Comment by wgcban** [comment]
@Cassiatora Please let me know if you need more clarification on it. Thanks.

**Comment by Cassiatora** [comment]
OK, I got it. Your clarification has been very detailed. Thank you for your patience.
