### ISSUE TITLE
 about the meaning of the feature images' names

### ISSUE THREAD

**Issue by Garsonjw** [wgcban/ddpm-cd#20]
Hi, 
I am interested in your work. And I have a question about the meaning of the feature images' names.
I got many feature images. And I want to know the meaning of the 'i' and the 'level'. Is it possible to map it to the 'multi-scale feature'?
![image](https://user-images.githubusercontent.com/128013411/225506173-48f3eccf-7956-40fa-a46e-79a6c27c7c00.png)

**Comment by wgcban** [comment]
@Garsonjw Hi, the level indicates the different levels of the unet and i indicate the different features of the corresponding level. For an example, Unet computes features at multiple scales like HxW, H/2 x W/2, so on. These are the different levels. At a given level, we get a set of features.

**Comment by Garsonjw** [comment]
thank you for your reply. The level of the feats is eleven(0 1 2 3 4 5 6 7 8 9 10). It is the number of ResnetBlocWithAttn in the upsampling module. But I do't konw which level HxW, H/2 x W/2, so on represents. In other words, how can I get the same images as Fig3.

**Comment by wgcban** [comment]
@Garsonjw yes, that is true. What you can do is print the shape of the feats for a given level.
