### ISSUE TITLE
Training diffusion model with remote sensing data

### ISSUE THREAD

**Issue by MLS2021** [wgcban/ddpm-cd#28]
Thank you for your work. I would like to ask if the data is labeled when you train the diffusion model with remote sensing data.

**Comment by wgcban** [comment]
@MLS2021 Yes, we used labeled data to fine-tune the change detection head. But, for pre-training the diffusion Unet we did not use any labeled data.

**Comment by MLS2021** [comment]
> @MLS2021 Yes, we used labeled data to fine-tune the change detection head. But, for pre-training the diffusion Unet we did not use any labeled data.

OK, thank you.
