### ISSUE TITLE
Data for pretraining the diffusion model

### ISSUE THREAD

**Issue by Jeff001128** [wgcban/ddpm-cd#29]
Dear author,

Thank you for the great work which has intrigued me a lot. 
I would like to kindly ask if the data used for pretraining the diffusion model can be provided.

Best,
Jeff

**Comment by wgcban** [comment]
Hi @Jeff001128 
Thank you!
We collected remote sensing images from publicly available RGB remote sensing datasets: LEVIR-CD (train-set), WHU-CD (train-set), DSIFN-CD (train-set), SeCo-100k images, and BigEarthNet images. Please download all the images from those dataset and dump inside a one folder prior to starting the diffusion training. Download links to some datasets can be found in my other repos like ChangeFormer, DDPM-CD, etc.
