### ISSUE TITLE
About the expansion of the pre-training dataset

### ISSUE THREAD

**Issue by dasimaduoshuaia** [wgcban/ddpm-cd#31]
Dear Author：
Thank you so much for this exciting work!

We note that you have collected a large amount of optical remote sensing images to pre-train the diffusion model. In order to explore the migration capability of your proposed method on multi-source remote sensing data, we would like to further expand this dataset with SAR images and retrain the diffusion model, so we take the liberty to ask you if you can provide us with your pre-training dataset.

Gratefully thanks for your consideration, and look forward your reply.

Dr.Wu

**Comment by wgcban** [comment]
Hi @dasimaduoshuaia 
Thank you! 
We collected remote sensing images from publicly available RGB remote sensing datasets: LEVIR-CD (train-set), WHU-CD (train-set), DSIFN-CD (train-set), SeCo-100k images, and BigEarthNet images.

**Comment by dasimaduoshuaia** [comment]
Dear Author：

It's great honor to receive your reply informing us of the composition of the pre-trained dataset！If there is any latest development, we will share with you in time.

Thank you again for your information.
