### ISSUE TITLE
Question for typo in paper

### ISSUE THREAD

**Issue by choidaedae** [wgcban/ddpm-cd#32]
Dear Author 

Hello, I am an UG student of POSTECH, Korea, and I am also an AI researcher in Meissaplanet. 
Thank you for open source about interesting model, DDPM-cd. 
As I read your paper, I found that there is some typo in it. 

<img width="975" alt="DDPMcd_typo" src="https://github.com/wgcban/ddpm-cd/assets/105369646/48d1304d-ce95-4ecb-a7a1-a8d74c59f6c9">

In line 4 for this paragraph, I think that the formula of posterior distribution should to be 'q(x_t|x_{t-1})', but you wrote it like <img width="89" alt="image" src="https://github.com/wgcban/ddpm-cd/assets/105369646/23168a40-bcdd-402c-9daf-93b1a02f4ba9">. 

Have a nice day :)

**Comment by wgcban** [comment]
@choidaedae Thank you for pointing out this. We will correct it in the future version.
