### ISSUE TITLE
Prediction Images Are All Black

### ISSUE THREAD

**Issue by abdulbb** [wgcban/ddpm-cd#33]
I have cloned the repository and downloaded all the necessary pre-trained models and datasets as per the documentation. However, when I run the code, it executes without any errors but the prediction images generated are just black.

![1](https://github.com/wgcban/ddpm-cd/assets/27974341/3d8e61a5-2228-4dd4-b4e1-345c66c91213)
![2](https://github.com/wgcban/ddpm-cd/assets/27974341/2566b29f-dec7-41f1-be9b-1f424562f85b)

**Comment by wgcban** [comment]
@abdulbb This is not an expected behavior. 
This could be due to not using proper model weights. Are you loading the correct pre-trained model?

**Comment by abdulbb** [comment]
So I changed the config in dsifn_test.json:
```json
{
    "name": "ddpm-RS-CDHead-DSIFN-[test]",
    "phase": "train", // train or test
    "gpu_ids": [
        0
    ],
    "path": { //set the paths
        "log": "logs",
        "tb_logger": "tb_logger",
        "results": "results",
        "checkpoint": "checkpoint",
        "resume_state": null
        //"resume_state": "ddpm/ddpm-cd-master/model/pre-trained/pretrained-cd-models/cd-dsifn-50-100-400/best_cd_model" 
    },
    "path_cd": { //set the path 
        "log": "logs",
        "tb_logger": "tb_logger",
        "results": "results",
        "checkpoint": "checkpoint",
        "resume_state": "/ddpm/ddpm-cd-master/model/pre-trained/pretrained-cd-models/cd-dsifn-50-100-400/best_cd_model" 
    }
```
after that I run: 

python ddpm_cd.py --config config/dsifn_test.json --phase test

Is that correct? Or am I doing something wrong? If it is, could you please explain how the steps are.

**Comment by wgcban** [comment]
@abdulbb sorry for the late reply? Did you able to resolve this issue?
