### ISSUE TITLE
Practicality of the model on 64x64 images

### ISSUE THREAD

**Issue by YluHuu** [wgcban/ddpm-cd#34]
Thank you for your work. I benefit a lot from it. I now want to train with 64x64 or smaller images. Does this model work? Do I need to change the` channel_multiplier` module in the `Unet` module? It means a lot to me. I appreciate it.

**Comment by YluHuu** [comment]
Thank you for your answer, it is very helpful to me

**Comment by YluHuu** [comment]
Hello my teacher, happy Teachers' Day. I am a novice who is learning the diffusion model, I am familiar with the theory, but I am still not clear about the code, I would like to know why I need to set three numbers for "t",such as "t": [50,150,400], I wonder if it is OK to set only one? I understand that t is to solve for x_t but why do I have to solve for x_t at three times at the same time?

**Comment by wgcban** [comment]
@YluHuu Hey, thanks for your question. The t denotes the amount of noise added to the clean image (i.e., noise variance). When extracting the features for the change detection task, we found out that, extracting features corresponds to multiple noise levels such as 50, 150, 400 improves the performance. Please check the ablation study on how the performance varies when you combine features corresponds to different noise levels. Although, you can use features corresponds to one noise level, the performance can be enhanced by combining multiple. 
![image](https://github.com/wgcban/ddpm-cd/assets/38159198/b0fbb2fe-7498-458f-b2bb-e8d0994406e5)

**Comment by YluHuu** [comment]
Thank you very much. I will try my best to continue my study and I hope I can get your guidance later😜😁

**Comment by wgcban** [comment]
@YluHuu Np.

**Comment by YluHuu** [comment]
Hello, when I read your code, I was a little confused about the Unet part. I think this code should be  `Encoder + Decoder` 's channels ?
```
ups.append(ResnetBlocWithAttn(
                    pre_channel+feat_channels.pop(), channel_mult, noise_level_emb_dim=noise_level_channel, norm_groups=norm_groups,
                        dropout=dropout, with_attn=use_attn))
                pre_channel = channel_mult
```
In addition, I would also like to know where the skip connections are made in the code and where the Encoder is used to add the feature graph of the Decoder

**Comment by YluHuu** [comment]
Hello, I would like to know why only transformer parameters need to be updated when fine-tuning ddpm?
``
