### ISSUE TITLE
When loading your pretraining file, errors may occur in the following model file sections due to structural mismatch between your pretraining model directly under the link and the ddpm model under ddpm_cd.

### ISSUE THREAD

**Issue by HZWXW371** [wgcban/ddpm-cd#36]
network.load_state_dict(torch.load(gen_path), strict=False)
            network.load_state_dict(torch.load(
                gen_path), strict=(not self.opt['model']['finetune_norm']))

                
            if self.opt['phase'] == 'train':
                #optimizer
                opt = torch.load(opt_path)
                self.optG.load_state_dict(opt['optimizer'])
                self.begin_step = opt['iter']
                self.begin_epoch = opt['epoch']

经debug查看strict=(not self.opt['model']['finetune_norm'])该语句执行严格匹配不通过，注释该语句后opt['optimizer']输入与初始化的optG参数格式确实不匹配，希望作者大大帮忙看一看谢谢

**Comment by HZWXW371** [comment]
strict=(not self_opt ['model']['finetune_norm']) The execution of the statement fails to match strictly. After commenting the statement, the opt['optimizer'] input does not match the initialization optG parameter format. Hope the author greatly help take a look thank you

**Comment by HZWXW371** [comment]
![image](https://github.com/wgcban/ddpm-cd/assets/84051927/c9b6bfea-d7d8-49ac-88af-33b445aecedd)

**Comment by Assioncreed** [comment]
我也遇到了这个问题，你是不是也将which_model_G设置为了ddpm？我估计是作者预训练好的模型是使用的sr3网络结构，所以就导致预训练的模型权重文件与当前模型的网络结构不匹配。

**Comment by yxzz1121** [comment]
how to solve it
