### ISSUE TITLE
Broken wandb link

### ISSUE THREAD

**Issue by robmarkcole** [wgcban/ddpm-cd#37]
In the main readme: 

Test results on wandb
[LEVIR-WHU-DSIFN-CDD-Test-Results](https://wandb.ai/wgcban/ddpm-RS-CDHead/reports/Change-Detection-Performance-on-Test-sets-of-LEVIR-CD-WHU-CD-DSIFN-CD-and-CDD--VmlldzoyMDE5NDg5?accessToken=6eikgovmk7ct25ar00eggsuslh8bzdz9e8215qn5xa0omqe5uo5u1jf4lh2liajx)

Gives 
<img width="888" alt="image" src="https://github.com/wgcban/ddpm-cd/assets/11855322/be078056-4761-4905-af3f-ca1e75ac94c0">

**Comment by wgcban** [comment]
@robmarkcole thank you for pointing out this. However, I have to delete these log files due to limited storage I have available at wandb for other project. These are just train/val/test logs and all the pre-trained models are still available in GitHub/dropbox.
