### ISSUE TITLE
FileNotFoundError: [Errorno 2] No such a file or directory:  ‘experiments/ddpm-RS-Unet_220819_161634

### ISSUE THREAD

**Issue by wo0423** [wgcban/ddpm-cd#5]
Excuse me, by reading the readme file, I know that the model should be trained first, but when I run ddpm_ Train reported such an error 
FileNotFoundError: [Errorno 2] No such a file or directory: ‘experiments/ddpm-RS-Unet_220819_161634
I don't know where I made a mistake, I would be grateful if you could reply

**Comment by wgcban** [comment]
Hi @wo0423 
Yes, you can start with training the diffusion model first if you wish (however, this may take several days to train), or else you can use the pre-trained diffusion model provided (I strongly recommend you to use the pre-trained diffusion model first). Can you pls copy and paste the full error details here?

**Comment by wo0423** [comment]
firstly，thx for your reply.i set the resume_state in “path”: "E:/I190000_E97_opt.pth" in the cdd.json,but when i run the ddpm_cd file, a similar error occured 
E:\anaconda\ana\python.exe E:/ddpm-cd-master/ddpm_cd.py
Traceback (most recent call last):
  File "E:/ddpm-cd-master/ddpm_cd.py", line 28, in <module>
    opt = Logger.parse(args)
  File "E:\ddpm-cd-master\core\logger.py", line 43, in parse
    mkdirs(opt['path'][key])
  File "E:\ddpm-cd-master\core\logger.py", line 11, in mkdirs
    os.makedirs(paths, exist_ok=True)
  File "E:\anaconda\ana\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "E:\anaconda\ana\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'experiments\\ddpm-RS-CDHead-CDD_220819_194305'

**Comment by wgcban** [comment]
@wo0423 The code assumes you save your model in ``experiments`` folder, as you can see from the error. 

- So, pls create a folder named ``experiments`` inside ``ddpm-cd-master``. 
- Then create  ``ddpm-RS-Unet_220426_160536/checkpoint/`` inside ``experiments and place both ``I190000_E97_opt.pth`` and ``I190000_E97_gen.pth`` in it. 
- In the config file you should mention only the first part of the pre-trained model, i.e. ``experiments/ddpm-RS-Unet_220426_160536/checkpoint/I110000_E88``.

**Comment by wo0423** [comment]
i got it,you are so nice,thx very much
