### ISSUE TITLE
Failed to download Pre-trained diffusion model

### ISSUE THREAD

**Issue by ChengxiHAN** [wgcban/ddpm-cd#6]
Hi, I am very interested about your code but failed to downed 'Pre-trained diffusion model' for many times, could you send it to my email: 1121399040@qq.com,very thanks.

**Comment by wgcban** [comment]
Hi @ChengxiHAN 
Have you tried to download the pre-trained models with the terminal?

For example, you can run the following code in the terminal:
```
wget https://www.dropbox.com/s/1q9bu7jmeyzxcbn/I190000_E97_gen.pth
```
and 
```
wget https://www.dropbox.com/s/41out218irscjfl/I190000_E97_opt.pth
```

**Comment by ChengxiHAN** [comment]
> 

Thanks for your reply. Actually, it still failed. Maybe you can upload it to Google Drive or Baidu  Drive or email? Very thanks.

**Comment by ChengxiHAN** [comment]
> @ChengxiHAN Could you try this google drive link: https://drive.google.com/file/d/1RXWtGdSNCBEAf7nr61uNyZP6HwNl_Zyi/view?usp=sharing

Thanks for your reply. I tried three times and failed three times. It stopped about 50% of the download process. I didn't know the reason. Could you upload them separately?  I will try it again until successful. Very thanks.

**Comment by ChengxiHAN** [comment]
> 



> > @ChengxiHAN Could you try this google drive link: https://drive.google.com/file/d/1RXWtGdSNCBEAf7nr61uNyZP6HwNl_Zyi/view?usp=sharing
> 
> Thanks for your reply. I tried three times and failed three times. It stopped about 50% of the download process. I didn't know the reason. Could you upload them separately? I will try it again until successful. Very thanks.

Good news. Just succeeded, thanks, bro!

**Comment by wgcban** [comment]
Nice!
