### ISSUE TITLE
How can I modify the code to use the ddpm-cd for multi-category change detection?

### ISSUE THREAD

**Issue by cll011** [wgcban/ddpm-cd#8]
Dear author:
I have a question, could you please help me answer it:  
how can I modify the code to use the ddpm-cd for multi-category change detection?
![image](https://user-images.githubusercontent.com/44308785/198215305-03847ee4-0766-44c4-9b84-716545150c6b.png)

**Comment by 1157504134** [comment]
This is the output latitude, right?

**Comment by wgcban** [comment]
@yes you just need to specify ``out_channels``=2 in the config file.
